local   all             all                                     scram-sha-256
hostssl banking        banking_app     0.0.0.0/0               scram-sha-256
hostssl keycloak       keycloak        0.0.0.0/0               scram-sha-256
hostssl all            banking_root    0.0.0.0/0               scram-sha-256
hostnossl all           all             0.0.0.0/0               reject
host    all             all             0.0.0.0/0               reject
